SS_error = norm((stress-SSEXP.stress)./(SSEXP.stress))./length(SSEXP.stress);

transient_error = ((norm((i1f1.stress-vulcan_stepDown1.stress)./mean(vulcan_stepDown1.stress))./length(vulcan_stepDown1.stress)) + ...
    (norm((i2f2.stress-vulcan_stepDown2.stress)./mean(vulcan_stepDown2.stress))./length(vulcan_stepDown2.stress)) + ...
    (norm((i3f3.stress-vulcan_stepDown3.stress)./mean(vulcan_stepDown3.stress))./length(vulcan_stepDown3.stress)) + ...
    (norm((i4f4.stress-vulcan_stepDown4.stress)./mean(vulcan_stepDown4.stress))./length(vulcan_stepDown4.stress)))/4;

fObj = SS_error + transient_error;