%% Error calculations

SS_error = norm((stress-shear_stress_SS)./(shear_stress_SS))...
        /length(shear_stress_SS);

transient_error_UDLAOS = ...
    ((norm((UDLAOS1.stress-Exp_stress1)./mean(Exp_stress1)))./length(Exp_stress1) + ...
    (norm((UDLAOS2.stress-Exp_stress2)./mean(Exp_stress2)))./length(Exp_stress2) + ...
    (norm((UDLAOS3.stress-Exp_stress3)./mean(Exp_stress3)))./length(Exp_stress3)) ...
    /3;

transient_error_SU = ((norm((SU1.stress-silica_stepUpi0p1f5))./mean(silica_stepUpi0p1f5)) + ...
    (norm((SU2.stress-silica_stepUpi0p1f2p5))./mean(silica_stepUpi0p1f2p5)) + ...
    (norm((SU3.stress-silica_stepUpi0p1f1))./mean(silica_stepUpi0p1f1)) + ...
    (norm((SU4.stress-silica_stepUpi0p1f0p5))./mean(silica_stepUpi0p1f0p5)) +...
    (norm((SU5.stress-silica_stepUpi0p1f0p25))./mean(silica_stepUpi0p1f0p25))) ...
    ./length(silica_stepUpTime)/5;

transient_error_SD = ((norm((SD1.stress-silica_stepDowni5f2p5))./mean(silica_stepDowni5f2p5)) + ...
    (norm((SD2.stress-silica_stepDowni5f1p0))./mean(silica_stepDowni5f1p0)) + ...
    (norm((SD3.stress-silica_stepDowni5f0p5))./mean(silica_stepDowni5f0p5)) + ...
    (norm((SD4.stress-silica_stepDowni5f0p1))./mean(silica_stepDowni5f0p1)))  ...
    ./length(silica_stepDownTime)/4;

fObj = SS_error + transient_error_SD + transient_error_SU;

fprintf("Transient step up error = %f\n", transient_error_SU);
fprintf("Transient UDLAOS error = %f\n", transient_error_UDLAOS);
fprintf("Transient step down error = %f\n", transient_error_SD);
fprintf("Steady state flow curve error = %f\n", SS_error);
fprintf("Total error = %1.15f\n", fObj);