%% Data for origin plots

% Steady state flow curves
% 1. Flow curve
writematrix([shear_rate,stress], ...
    "Origin_plot_data/Armstrongetal_Flowcurve_model.csv", ...
    "Delimiter",",")

% 2. Volume fraction (Structure)
writematrix([shear_rate, phi_a'], ...
    "Origin_plot_data/Armstrongetal_Volume_fraction_model.csv", ...
    "Delimiter",",");

% 3. Step down transients

writematrix([time, SD1.stress', SD2.stress', SD3.stress', SD4.stress'], ...
    "Origin_plot_data/Armstrongetal_SD_transient_model.csv", ...
    "Delimiter",",");

writematrix([silica_stepDownTime, silica_stepDowni5f2p5, ...
    silica_stepDowni5f1p0,  silica_stepDowni5f0p5, ...
    silica_stepDowni5f0p1], ...
    "Origin_plot_data/Armstrongetal_SD_transient_experiments.csv", ...
    "Delimiter",",");

% 4. Step up transients