%% Data for origin plots

% % Steady state flow curves
% % 1. Flow curve
% writematrix([shear_rate,stress, silica_SS(:,2)], ...
%     "Origin_plot_data/Armstrongetal_Flowcurve_model.csv", ...
%     "Delimiter",",")
% 
% % 2. Volume fraction (Structure)
% writematrix([shear_rate, phi_a'], ...
%     "Origin_plot_data/Armstrongetal_Volume_fraction_model.csv", ...
%     "Delimiter",",");
% 
% % 3. Step down transients
% writematrix([time, SD1.stress', SD2.stress', SD3.stress', SD4.stress'], ...
%     "Origin_plot_data/Armstrongetal_SD_transient_model.csv", ...
%     "Delimiter",",");
% 
% writematrix([silica_stepDownTime, silica_stepDowni5f2p5, ...
%     silica_stepDowni5f1p0,  silica_stepDowni5f0p5, ...
%     silica_stepDowni5f0p1], ...
%     "Origin_plot_data/Armstrongetal_SD_transient_experiments.csv", ...
%     "Delimiter",",");
% 
% % 4. Step up transients
% writematrix([time, SU1.stress', SU2.stress', SU3.stress', SU4.stress', SU5.stress'], ...
%     "Origin_plot_data/Armstrongetal_SU_transient_model.csv", ...
%     "Delimiter",",");
% 
% writematrix([silica_stepUpTime, silica_stepUpi0p1f5, ...
%     silica_stepUpi0p1f2p5, ...
%     silica_stepUpi0p1f1, ...
%     silica_stepUpi0p1f0p5, ...
%     silica_stepUpi0p1f0p25], ...
%     "Origin_plot_data/Armstrongetal_SU_transient_experiments.csv", ...
%     "Delimiter",",");

% 5. LAOS
% omega = 0.01
writematrix([LAOS0p01_1.strain', LAOS0p01_1.shear_rate', LAOS0p01_1.stress', ...
    LAOS0p01_10.strain', LAOS0p01_10.shear_rate', LAOS0p01_10.stress', ...
    LAOS0p01_100.strain', LAOS0p01_100.shear_rate', LAOS0p01_100.stress', ...
    LAOS0p01_1000.strain', LAOS0p01_1000.shear_rate', LAOS0p01_1000.stress'], ...
    "Origin_plot_data/Armstrongetal_LAOS_omega_0p01.csv", ...
    "Delimiter",",");

% omega = 0.1
writematrix([ LAOS0p1_0p1.strain', LAOS0p1_0p1.shear_rate', LAOS0p1_0p1.stress', ......
    LAOS0p1_1.strain', LAOS0p1_1.shear_rate', LAOS0p1_1.stress', ...
    LAOS0p1_10.strain', LAOS0p1_10.shear_rate', LAOS0p1_10.stress', ...
    LAOS0p1_100.strain', LAOS0p1_100.shear_rate', LAOS0p1_100.stress', ...
    LAOS0p1_1000.strain', LAOS0p1_1000.shear_rate', LAOS0p1_1000.stress'], ...
    "Origin_plot_data/Armstrongetal_LAOS_omega_0p1.csv", ...
    "Delimiter",",");

% omega = 1
writematrix([ LAOS1_0p1.strain', LAOS1_0p1.shear_rate', LAOS1_0p1.stress', ......
    LAOS1_1.strain', LAOS1_1.shear_rate', LAOS1_1.stress', ...
    LAOS1_10.strain', LAOS1_10.shear_rate', LAOS1_10.stress', ...
    LAOS1_100.strain', LAOS1_100.shear_rate', LAOS1_100.stress'], ...
    "Origin_plot_data/Armstrongetal_LAOS_omega_1.csv", ...
    "Delimiter",",");

% omega = 10
writematrix([ LAOS10_0p1.strain', LAOS10_0p1.shear_rate', LAOS10_0p1.stress', ......
    LAOS10_1.strain', LAOS10_1.shear_rate', LAOS10_1.stress', ...
    LAOS10_10.strain', LAOS10_10.shear_rate', LAOS10_10.stress'], ...
    "Origin_plot_data/Armstrongetal_LAOS_omega_10.csv", ...
    "Delimiter",",");
