function dX = shearStressDE(obj, t, sigma, shearRate, logintMu)
% Differential equation for shear stress based on Saramito model with
% explicit yield stress and thermodynamically consistent
% elasto-visco-plasticity.
phi = obj.phi_a(logintMu);

dX = real( ...
    -(sigma - obj.cnst.sigma_y0*sign(shearRate)) ...
    + obj.cnst.mu_s*obj.eta(phi, logintMu)*shearRate ...
    )...
    /obj.tau(logintMu,shearRate);
end