function dX = shearStressDE(obj, ~, sigma, shear_rate, logintMu, A)
% Differential equation for shear stress based on Saramito model with
% explicit yield stress and thermodynamically consistent
% elasto-visco-plasticity.
phi = obj.phi_a(logintMu);

% dX = real( ...
%     -max([0,abs(sigma_eff(obj,sigma,logintMu, A)) - obj.sigma_y(logintMu)])*sign(sigma_eff(obj,sigma,logintMu, A)) ...
%     + obj.cnst.mu_s*obj.eta(phi, logintMu)*shear_rate ...
%     )...
%     /obj.tau(logintMu);

dX = real( ...
    -abs(sigma_eff(obj,sigma,logintMu, A)) + obj.sigma_y(logintMu)*sign(sigma_eff(obj,sigma,logintMu, A)) ...
    + obj.cnst.mu_s*obj.eta(phi, logintMu)*shear_rate ...
    )...
    /obj.tau(logintMu);
end