%% Wei et al. Steady state figures
% 1. Flow curve
writematrix([shear_rate,stress], ...
    "Origin_plot_data/Weietal_Flowcurve_model.csv", ...
    "Delimiter",",")

% 2. Volume fraction (Structure)
writematrix([shear_rate, phi_a'], ...
    "Origin_plot_data/Weietal_Volume_fraction_model.csv", ...
    "Delimiter",",");