%% Wei et al. Steady state figures
% 1. Flow curve
writematrix([shear_rate,stress], ...
    "Origin_plot_data/Weietal_Flowcurve_model.csv", ...
    "Delimiter",",")

% 2. Volume fraction (Structure)
writematrix([shear_rate, phi_a'], ...
    "Origin_plot_data/Weietal_Volume_fraction_model.csv", ...
    "Delimiter",",");

% 3. Transient plots
writematrix([StepDownEXP.i0p1f1_t, ...
    i1f1.stress', ...
    i2f2.stress', ...
    i3f3.stress'], ...
    "Origin_plot_data/Weietal_transient_fits_model.csv", ...
    "Delimiter",",");

writematrix([StepDownEXP.i0p1f1_t, ...
    i1f1.phi_a', ...
    i2f2.phi_a', ...
    i3f3.phi_a'], ...
    "Origin_plot_data/Weietal_transient_phi_a_model.csv", ...
    "Delimiter",",");


writematrix([StepDownEXP.i0p1f1_t, ...
    StepDownEXP.i0p1f1_stress, ...
    StepDownEXP.i0p1f2p5_stress, ...
    StepDownEXP.i0p1f5_stress], ...
    "Origin_plot_data/Weietal_transient_fits_experiment.csv", ...
    "Delimiter",",");

% 4. Flow reversal
writematrix([rev(2).time'*0.5, rev(2).stress'./rev(2).stress(end), ...
    rev(3).time'*2.5, rev(3).stress'./rev(3).stress(end), ...
    rev(4).time'*5.0, rev(4).stress'./rev(4).stress(end), ...
    rev(5).time'*10, rev(5).stress'./rev(5).stress(end), ...
    rev(6).time'*20, rev(6).stress'./rev(6).stress(end) ...
    ], "Origin_plot_data/Weietal_transient_reversal_predictions.csv", ...
    "Delimiter",",");
